/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto_compi1_vj26.frontend;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Insets;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 * Componente que representa una pestaña del editor. Contiene: - JTextArea
 * principal (editor de código) - LineNumberPanel a la izquierda - JScrollPane
 * que los envuelve
 *
 * También guarda la ruta del archivo (.glt) asociado, y un flag de "modificado"
 * para el título con asterisco.
 *
 * @author david
 */
public class EditorTab extends javax.swing.JPanel {

    private static final Font EDITOR_FONT = new Font("Monospaced", Font.PLAIN, 13);

    private final JTextArea editor;
    private File file;  // null si el archivo no ha sido guardado aún
    private boolean modified;

    public EditorTab(File file, String content) {
        super(new BorderLayout());
        this.file = file;
        this.modified = false;

        // ---  Editor ---
        this.editor = new JTextArea(content);
        this.editor.setFont(EDITOR_FONT);
        this.editor.setTabSize(4);
        this.editor.setLineWrap(false);
        this.editor.setBackground(Color.WHITE);
        this.editor.setForeground(new Color(30, 30, 30));
        this.editor.setCaretColor(new Color(30, 30, 30));
        this.editor.setMargin(new Insets(4, 6, 4, 6));

        // Marcar como modificado al escribir
        this.editor.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                setModified(true);
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                setModified(true);
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
            }
        });

        // --- Números de línea ---
        LineNumber lineNumbers = new LineNumber(editor);

        // --- ScrollPane ---
        JScrollPane scroll = new JScrollPane(editor);
        scroll.setRowHeaderView(lineNumbers);
        scroll.setBorder(BorderFactory.createEmptyBorder());
        scroll.getVerticalScrollBar().setUnitIncrement(16);

        add(scroll, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // --- API pública ---
    public JTextArea getEditor() {
        return editor;
    }

    public String getText() {
        return editor.getText();
    }

    public File getFile() {
        return file;
    }

    public boolean isModified() {
        return modified;
    }

    public void setFile(File f) {
        this.file = f;
        setModified(false);
    }

    public void setModified(boolean m) {
        this.modified = m;
        // La ventana principal escucha cambios de estado a través del DocumentListener
        // y actualiza el título de la pestaña cuando sea necesario.
    }

    /**
     * Nombre que debe aparecer en la pestaña. Si el archivo no tiene nombre
     * aún: "sin_titulo.glt" Si fue modificado: agrega " *" al final
     *
     * @return
     */
    public String getTabTitle() {
        String name = (this.file != null) ? this.file.getName() : "sin_titulo.glt";
        return this.modified ? name + " *" : name;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
