/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto_compi1_vj26.frontend;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Insets;
import java.io.File;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.text.Element;

/**
 * Componente que representa una pestaña del editor. Contiene: - JTextArea
 * principal (editor de codigo) - JTextArea a la izquierda (contador de lineas)
 * - JScrollPane que los envuelve
 *
 * Tambien guarda la ruta del archivo (.glt) asociado, y un flag de "modificado"
 * para el titulo con asterisco.
 *
 * @author david
 */
public class EditorTab extends javax.swing.JPanel {

    private static final Font EDITOR_FONT = new Font("Monospaced", Font.PLAIN, 13);

    private final JTextArea editor;
    private final JTextArea lineNumbers;
    private final JScrollPane scrollPane;
    private File file;  // null si el archivo no ha sido guardado aun
    private boolean modified;

    public EditorTab(File file, String content) {
        super(new BorderLayout());
        this.file = file;
        this.modified = false;

        // ---  Editor ---
        this.editor = new JTextArea(content);
        this.editor.setFont(EDITOR_FONT);
        this.editor.setTabSize(4);
        this.editor.setLineWrap(false);
        this.editor.setBackground(Color.WHITE);
        this.editor.setForeground(new Color(30, 30, 30));
        this.editor.setCaretColor(new Color(30, 30, 30));
        this.editor.setMargin(new Insets(0, 6, 0, 6));

        // --- Numeros de linea ---
        this.lineNumbers = new JTextArea("1");
        this.lineNumbers.setBackground(new Color(220, 220, 220));
        this.lineNumbers.setForeground(Color.DARK_GRAY);
        this.lineNumbers.setFont(EDITOR_FONT);
        this.lineNumbers.setEditable(false);
        this.lineNumbers.setFocusable(false);
        // Alinear el texto a la derecha con un margen
        this.lineNumbers.setMargin(new Insets(0, 5, 0, 10));

        // --- ScrollPane ---
        this.scrollPane = new JScrollPane(this.editor);

        // Usar el panel de lineas como rowHeader del scrollPane.
        // Esto sincroniza automaticamente el scroll vertical de ambos.
        this.scrollPane.setRowHeaderView(this.lineNumbers);

        // Marcar como modificado al escribir
        this.editor.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                setModified(true);
                updateLineNumbers();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                setModified(true);
                updateLineNumbers();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                updateLineNumbers();
            }
        });

        add(this.scrollPane, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // --- API publica ---
    public JTextArea getEditor() {
        return editor;
    }

    public String getText() {
        return editor.getText();
    }

    public File getFile() {
        return file;
    }

    public boolean isModified() {
        return modified;
    }

    public void setFile(File f) {
        this.file = f;
        setModified(false);
    }

    public void setModified(boolean m) {
        this.modified = m;
        // La ventana principal escucha cambios de estado a traves del DocumentListener
        // y actualiza el titulo de la pestaña cuando sea necesario.
    }

    /**
     * Nombre que debe aparecer en la pestaña. Si el archivo no tiene nombre
     * aun: "sin_titulo.glt" Si fue modificado: agrega " *" al final
     *
     * @return
     */
    public String getTabTitle() {
        String name = (this.file != null) ? this.file.getName() : "sin_titulo.glt";
        return this.modified ? name + " *" : name;
    }

    /**
     * Calcula y actualiza el texto del panel de numeracion.
     */
    private void updateLineNumbers() {
        String text = editor.getText();
        if (text == null) {
            return;
        }

        // Contar el numero de lineas basandose en los saltos de linea (\n)
        int caretPosition = this.editor.getDocument().getLength();
        Element root = this.editor.getDocument().getDefaultRootElement();
        StringBuilder numbers = new StringBuilder("1");

        for (int i = 2; i <= root.getElementCount(); i++) {
            numbers.append("\n").append(i);
        }

        // Para asegurar que la alineacion vertical sea perfecta con la fuente monoespaciada
        // debemos añadir un espacio extra si la linea de texto termina en un salto.
        if (text.endsWith("\n") && caretPosition > 0) {
            numbers.append("\n ");
        }

        this.lineNumbers.setText(numbers.toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
