/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_compi1_vj26.frontend;

import com.mycompany.proyecto_compi1_vj26.Lexer;
import com.mycompany.proyecto_compi1_vj26.ast.ProgramNode;
import com.mycompany.proyecto_compi1_vj26.models.ErrorReport;
import com.mycompany.proyecto_compi1_vj26.models.ReportType;
import com.mycompany.proyecto_compi1_vj26.models.Token;
import com.mycompany.proyecto_compi1_vj26.parser;
import com.mycompany.proyecto_compi1_vj26.symbols.Symbol;
import com.mycompany.proyecto_compi1_vj26.visitor.interpreter.InterpreterVisitor;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Insets;
import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * Ventana principal del IDE GoLite.
 *
 * @author david
 */
public class IDEGoLite extends JFrame {

    // --- Componentes principales ---
    private final JTabbedPane tabbedPane;
    private final JTextArea console;

    // --- Estado de pestañas ---
    private final List<EditorTab> tabs = new ArrayList<>();

    // --- Colores de consola ---
    private static final Color CONSOLE_BG = new Color(18, 18, 18);
    private static final Color CONSOLE_FG = new Color(200, 255, 200);
    private static final Color CONSOLE_ERROR = new Color(255, 100, 100);
    private static final Color CONSOLE_INFO = new Color(100, 180, 255);
    
    private static final String AST_OUTPUT_DIR = "ast_output";

    /**
     * Creates new form IDEGoLite
     */
    public IDEGoLite() {
        super("GoLite IDE");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(1000, 720);
        setMinimumSize(new Dimension(750, 520));
        setLocationRelativeTo(null);

        // --- Menu ---
        setJMenuBar(this.buildMenuBar());

        // --- Pestañas del editor ---
        this.tabbedPane = new JTabbedPane(JTabbedPane.TOP);
        this.tabbedPane.setFont(new Font("SansSerif", Font.PLAIN, 12));
        this.tabbedPane.setBorder(BorderFactory.createEmptyBorder(4, 4, 0, 4));

        // --- Consola ---
        this.console = new JTextArea();
        this.console.setEditable(false);
        this.console.setFont(new Font("Monospaced", Font.PLAIN, 13));
        this.console.setBackground(CONSOLE_BG);
        this.console.setForeground(CONSOLE_FG);
        this.console.setCaretColor(CONSOLE_FG);
        this.console.setMargin(new Insets(8, 10, 8, 10));

        JScrollPane consoleScroll = new JScrollPane(this.console);
        consoleScroll.setBorder(BorderFactory.createLineBorder(new Color(60, 60, 60)));

        JPanel consolePanel = new JPanel(new BorderLayout());
        consolePanel.add(buildConsoleHeader(), BorderLayout.NORTH);
        consolePanel.add(consoleScroll, BorderLayout.CENTER);

        // --- Split vertical ---
        JSplitPane split = new JSplitPane(JSplitPane.VERTICAL_SPLIT, tabbedPane, consolePanel);
        split.setResizeWeight(0.62);
        split.setDividerSize(5);
        split.setContinuousLayout(true);
        split.setBorder(BorderFactory.createEmptyBorder(4, 6, 6, 6));

        add(split, BorderLayout.CENTER);

        // Abrir con una pestaña vacía por defecto
        this.newTab(null, "");

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // --- Barra de menú ---
    private JMenuBar buildMenuBar() {
        JMenuBar menuBar = new JMenuBar();
        menuBar.setBackground(new Color(245, 245, 245));

        // --- Archivo ---
        JMenu menuArchivo = new JMenu("Archivo");
        this.addMenuItem(menuArchivo, "Nuevo", KeyStroke.getKeyStroke(KeyEvent.VK_N, InputEvent.CTRL_DOWN_MASK), e -> this.newTab(null, ""));
        this.addMenuItem(menuArchivo, "Abrir...", KeyStroke.getKeyStroke(KeyEvent.VK_O, InputEvent.CTRL_DOWN_MASK), e -> this.openFile());
        menuArchivo.addSeparator();
        this.addMenuItem(menuArchivo, "Guardar", KeyStroke.getKeyStroke(KeyEvent.VK_S, InputEvent.CTRL_DOWN_MASK), e -> this.saveCurrentTab());
        this.addMenuItem(menuArchivo, "Guardar como...", null, e -> this.saveCurrentTabAs());
        menuArchivo.addSeparator();
        this.addMenuItem(menuArchivo, "Salir", KeyStroke.getKeyStroke(KeyEvent.VK_Q, InputEvent.CTRL_DOWN_MASK), e -> System.exit(0));

        // --- Herramientas ---
        JMenu menuHerramientas = new JMenu("Herramientas");
        this.addMenuItem(menuHerramientas, "Ejecutar", KeyStroke.getKeyStroke(KeyEvent.VK_F5, 0), e -> this.ejecutar());

        // --- Rreportes ---
        JMenu menuReportes = new JMenu("Reportes");
        this.addMenuItem(menuReportes, "Tabla de Tokens", null, e -> this.mostrarUltimoReporteTokens());
        this.addMenuItem(menuReportes, "Tabla de Errores", null, e -> this.mostrarUltimoReporteErrores());
        this.addMenuItem(menuReportes, "Tabla de Símbolos", null, e -> this.mostrarUltimoReporteSimbolos());
        this.addMenuItem(menuReportes, "Arbol AST", null, e -> this.mostrarUltimoReporteAST());

        // --- Ayuda ---
        JMenu menuAyuda = new JMenu("Ayuda");
        this.addMenuItem(menuAyuda, "Acerca de...", null, e -> this.mostrarAcercaDe());

        // --- Botón Ejecutar ---
        JButton btnEjecutar = new JButton("Ejecutar");
        btnEjecutar.setFont(new Font("SansSerif", Font.BOLD, 13));
        btnEjecutar.setBackground(new Color(60, 60, 60));
        btnEjecutar.setForeground(Color.WHITE);
        btnEjecutar.setFocusPainted(false);
        btnEjecutar.setBorderPainted(false);
        btnEjecutar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnEjecutar.setMargin(new Insets(4, 16, 4, 16));
        btnEjecutar.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                btnEjecutar.setBackground(new Color(40, 160, 80));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                btnEjecutar.setBackground(new Color(60, 60, 60));
            }
        });
        btnEjecutar.addActionListener(e -> this.ejecutar());

        menuBar.add(menuArchivo);
        menuBar.add(menuHerramientas);
        menuBar.add(menuReportes);
        menuBar.add(menuAyuda);
        menuBar.add(Box.createHorizontalGlue());
        menuBar.add(btnEjecutar);
        menuBar.add(Box.createRigidArea(new Dimension(8, 0)));

        return menuBar;
    }

    private void addMenuItem(JMenu menu, String title, KeyStroke shortcut, ActionListener action) {
        JMenuItem item = new JMenuItem(title);
        item.setFont(new Font("SansSerif", Font.PLAIN, 12));
        if (shortcut != null) {
            item.setAccelerator(shortcut);
        }
        item.addActionListener(action);
        menu.add(item);
    }

    // --- Header de la consola ---
    private JPanel buildConsoleHeader() {
        JPanel header = new JPanel(new BorderLayout());
        header.setBackground(new Color(45, 45, 45));
        header.setBorder(BorderFactory.createEmptyBorder(3, 10, 3, 6));

        JLabel label = new JLabel("Consola");
        label.setFont(new Font("SansSerif", Font.BOLD, 12));
        label.setForeground(new Color(200, 200, 200));

        JButton btnLimpiar = new JButton("Limpiar");
        btnLimpiar.setFont(new Font("SansSerif", Font.PLAIN, 11));
        btnLimpiar.setForeground(new Color(180, 180, 180));
        btnLimpiar.setBackground(new Color(70, 70, 70));
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.setFocusPainted(false);
        btnLimpiar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(e -> console.setText(""));

        header.add(label, BorderLayout.WEST);
        header.add(btnLimpiar, BorderLayout.EAST);
        return header;
    }

    // --- Gestión de pestañas ---
    private void newTab(File file, String content) {
        EditorTab tab = new EditorTab(file, content);
        tabs.add(tab);

        int index = this.tabbedPane.getTabCount();
        this.tabbedPane.addTab(null, tab);

        TabHeader header = new TabHeader(this.tabbedPane, tab.getTabTitle(), () -> closeTab(tab));
        this.tabbedPane.setTabComponentAt(index, header);
        this.tabbedPane.setSelectedIndex(index);

        // Actualizar titulo de la pestaña cuando el editor cambia
        tab.getEditor().getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                updateTabTitle(tab, header);
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                updateTabTitle(tab, header);
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
            }
        });
    }

    private void closeTab(EditorTab tab) {
        int idx = tabs.indexOf(tab);
        if (idx < 0) {
            return;
        }

        if (tab.isModified()) {
            int opt = JOptionPane.showConfirmDialog(this,
                    "¿Guardar los cambios en \"" + tab.getTabTitle().replace(" *", "") + "\" antes de cerrar?",
                    "Cambios sin guardar",
                    JOptionPane.YES_NO_CANCEL_OPTION);
            if (opt == JOptionPane.CANCEL_OPTION) {
                return;
            }
            if (opt == JOptionPane.YES_OPTION) {
                saveTab(tab);
            }
        }

        tabs.remove(idx);
        this.tabbedPane.removeTabAt(idx);

        // Siempre tener al menos una pestaña abierta
        if (tabs.isEmpty()) {
            newTab(null, "");
        }
    }

    private void updateTabTitle(EditorTab tab, TabHeader header) {
        SwingUtilities.invokeLater(() -> header.setTitle(tab.getTabTitle()));
    }

    private EditorTab currentTab() {
        int idx = this.tabbedPane.getSelectedIndex();
        return (idx >= 0 && idx < tabs.size()) ? tabs.get(idx) : null;
    }

    // --- Archivo: Abrir / Guardar ---
    private void openFile() {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileNameExtensionFilter("Archivos GoLite (*.glt)", "glt"));
        if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File file = chooser.getSelectedFile();
        try {
            String content = Files.readString(file.toPath(), StandardCharsets.UTF_8);
            this.newTab(file, content);
        } catch (IOException ex) {
            this.consolePrintError("Error al abrir el archivo: " + ex.getMessage());
        }
    }

    private void saveCurrentTab() {
        EditorTab tab = this.currentTab();
        if (tab == null) {
            return;
        }
        if (tab.getFile() == null) {
            this.saveCurrentTabAs();
        } else {
            this.saveTab(tab);
        }
    }

    private void saveCurrentTabAs() {
        EditorTab tab = this.currentTab();
        if (tab == null) {
            return;
        }

        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileNameExtensionFilter("Archivos GoLite (*.glt)", "glt"));
        if (chooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File file = chooser.getSelectedFile();
        if (!file.getName().endsWith(".glt")) {
            file = new File(file.getAbsolutePath() + ".glt");
        }
        tab.setFile(file);
        this.saveTab(tab);
    }

    private void saveTab(EditorTab tab) {
        try {
            Files.writeString(tab.getFile().toPath(), tab.getText(), StandardCharsets.UTF_8);
            tab.setModified(false);
            // Refrescar titulo de la pestaña
            int idx = tabs.indexOf(tab);
            if (idx >= 0) {
                Component comp = tabbedPane.getTabComponentAt(idx);
                if (comp instanceof TabHeader th) {
                    th.setTitle(tab.getTabTitle());
                }
            }
            consolePrintInfo("Archivo guardado: " + tab.getFile().getName());
        } catch (IOException ex) {
            this.consolePrintError("Error al guardar: " + ex.getMessage());
        }
    }

    // --- Ejecucion del interprete ---
    // Guardamos el último resultado para poder mostrarlo en los reportes
    private List<Token> lastTokens = new ArrayList<>();
    private List<ErrorReport> lastErrors = new ArrayList<>();
    private List<Symbol> lastSymbols = new ArrayList<>();
    private ProgramNode lastAST = null;

    private void ejecutar() {
        EditorTab tab = this.currentTab();
        if (tab == null) {
            return;
        }

        String source = tab.getText().trim();
        if (source.isEmpty()) {
            consolePrintError("El editor esta vacio.");
            return;
        }

        String fileName = (tab.getFile() != null) ? tab.getFile().getName() : "sin_titulo.glt";
        this.console.append("> Ejecutando " + fileName + " ...\n");

        try {
            // 1. --- Analisis lexico ---
            Lexer lexer = new Lexer(new java.io.StringReader(source));

            // 2. --- Analisis sintactico ---
            parser p = new parser(lexer);
            ProgramNode ast;
            try {
                ast = (ProgramNode) p.parse().value;
                this.lastAST = ast;
            } catch (Exception e) {
                this.consolePrintError("[ERROR SINTÁCTICO] " + e.getMessage());
                this.lastTokens = lexer.getTokenList();
                this.lastErrors = new ArrayList<>(lexer.getLexicalErrors());
                this.lastErrors.addAll(p.getSyntaxErrors());
                this.mostrarResumenErrores(this.lastErrors);
                return;
            }

            // Recolectar tokens y errores lexicos/sintacticos
            this.lastTokens = lexer.getTokenList();
            this.lastErrors = new ArrayList<>();
            this.lastErrors.addAll(lexer.getLexicalErrors());
            this.lastErrors.addAll(p.getSyntaxErrors());

            // Si hay errores lexicos o sintacticos: avisar
            if (!this.lastErrors.isEmpty()) {
                JOptionPane.showMessageDialog(
                        this,
                        "Hay errores dentro del codigo. Revisa el reporte de errores!!!",
                        "Alerta de errores",
                        JOptionPane.ERROR_MESSAGE
                );
                this.consolePrintError("[INFO] Compilacion fallida — " + this.lastErrors.size() + " error(es) encontrados.");
                this.mostrarResumenErrores(this.lastErrors);
            }

            // --- 3. Interpretacion ---
            this.consolePrintInfo("[INFO] Compilacion iniciada");
            InterpreterVisitor interpreter = new InterpreterVisitor();
            interpreter.visit(ast);

            // Capturar el historial de simbolos para el reporte
            this.lastSymbols = interpreter.getSymbolTable().getAllDeclaredSymbols();

            // --- 4. Output del programa ---
            String output = interpreter.getOutput();
            if (!output.isEmpty()) {
                this.console.append(output);
            }

            // --- 5. Errores semanticos ---
            List<ErrorReport> semErrors = interpreter.getSemanticErrors();
            this.lastErrors.addAll(semErrors);

            if (semErrors.isEmpty()) {
                consolePrintInfo("[INFO] Ejecucion completada sin errores.\n");
            } else {
                this.consolePrintError("[INFO] Ejecucion con " + semErrors.size() + " error(es) semantico(s).\n");
                this.mostrarResumenErrores(semErrors);
            }

        } catch (Exception ex) {
            this.consolePrintError("[ERROR INESPERADO] " + ex.getMessage());
            ex.printStackTrace();
        }

        // Hacer scroll al final de la consola
        this.console.setCaretPosition(this.console.getDocument().getLength());
    }

    // --- Consola: utilidades de escritura
    private void consolePrintInfo(String msg) {
        this.console.append(msg + "\n");
    }

    private void consolePrintError(String msg) {
        this.console.append(msg + "\n");
    }

    private void mostrarResumenErrores(List<ErrorReport> errors) {
        for (ErrorReport e : errors) {
            this.console.append(String.format("  [%s] Linea %d, Col %d: %s%n",
                    e.getType().getType(), e.getLine(), e.getColumn(), e.getDescription()));
        }
    }

    // --- Reportes ---
    private void mostrarUltimoReporteTokens() {
        if (this.lastTokens.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No hay tokens disponibles. Ejecuta el codigo primero.",
                    "Reporte de Tokens", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        new ReportFrame(ReportType.TOKENS, this.lastTokens).setVisible(true);
    }

    private void mostrarUltimoReporteErrores() {
        if (this.lastErrors.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No se encontraron errores en la ultima ejecucion.",
                    "Reporte de Errores", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        new ReportFrame(ReportType.ERRORS, this.lastErrors).setVisible(true);
    }

    private void mostrarUltimoReporteSimbolos() {
        if (this.lastSymbols.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No hay símbolos disponibles. Ejecuta el código primero.",
                    "Reporte de Tabla de Símbolos", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        new ReportFrame(ReportType.SYMBOLS, this.lastSymbols).setVisible(true);
    }

    private void mostrarUltimoReporteAST() {
        if (this.lastAST == null) {
            JOptionPane.showMessageDialog(this,
                    "No hay AST disponible. Ejecuta el código primero.",
                    "Reporte de AST", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        try {
            // 1. Generar el DOT
            ASTGraphBuilder builder = new ASTGraphBuilder();
            String dotContent = builder.build(this.lastAST);

            // 2. Crear carpeta de salida fija en la raiz del proyecto
            File outDir = new File(AST_OUTPUT_DIR);
            if (!outDir.exists()) {
                outDir.mkdirs();
            }
            File dotFile = new File(outDir, "ast.dot");
            File pngFile = new File(outDir, "ast.svg");

            java.nio.file.Files.writeString(dotFile.toPath(), dotContent);

            // 3. Invocar graphviz
            ProcessBuilder pb = new ProcessBuilder(
                    "dot", "-Tsvg", dotFile.getAbsolutePath(), "-o", pngFile.getAbsolutePath()
            );
            pb.redirectErrorStream(true);
            Process proc = pb.start();
            int exitCode = proc.waitFor();

            if (exitCode != 0) {
                String errorOutput = new String(proc.getInputStream().readAllBytes());
                JOptionPane.showMessageDialog(this,
                        "Graphviz finalizó con errores (código " + exitCode + "):\n" + errorOutput,
                        "Error al generar AST", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!pngFile.exists()) {
                JOptionPane.showMessageDialog(this,
                        "Graphviz no generó la imagen esperada en " + pngFile.getAbsolutePath(),
                        "Error al generar AST", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 4. Mostrar la imagen en la ventana de reporte
            new ASTReportFrame(pngFile).setVisible(true);

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                    "No se pudo invocar Graphviz (¿está 'dot' en el PATH?):\n" + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            JOptionPane.showMessageDialog(this,
                    "La generación del AST fue interrumpida.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // --- Ayuda ---
    private void mostrarAcercaDe() {
        JOptionPane.showMessageDialog(this, """
                                            GoLite IDE
                                            Interprete del lenguaje GoLite
                                            
                                            Desarrollado con Java + JFlex + CUP
                                            Laboratorio de Organizacion de Lenguajes y Compiladores 1""",
                "Acerca de GoLite IDE",
                JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
