/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto_compi1_vj26.frontend;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JTextArea;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 * Panel que muestra los números de línea a la izquierda del editor. Se
 * sincroniza automáticamente con el JTextArea asociado.
 *
 * @author david
 */
public class LineNumber extends javax.swing.JPanel {

    private static final Font LINE_FONT = new Font("Monospaced", Font.PLAIN, 13);
    private static final Color BG_COLOR = new Color(240, 240, 240);
    private static final Color FG_COLOR = new Color(120, 120, 120);
    private static final int PADDING = 8;

    private final JTextArea textArea;

    public LineNumber(JTextArea textArea) {
        this.textArea = textArea;
        setBackground(BG_COLOR);
        setFont(LINE_FONT);
        setPreferredSize(new Dimension(45, 0));

        // Repintar cada vez que el documento cambia
        textArea.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                repaint();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                repaint();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                repaint();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,
                RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
        g2.setFont(LINE_FONT);
        g2.setColor(FG_COLOR);

        FontMetrics fm = g2.getFontMetrics();
        int lineHeight = this.textArea.getFontMetrics(this.textArea.getFont()).getHeight();
        int startY = this.textArea.getInsets().top + fm.getAscent();

        int lineCount = this.textArea.getLineCount();
        for (int i = 1; i <= lineCount; i++) {
            String num = String.valueOf(i);
            int x = getWidth() - fm.stringWidth(num) - PADDING;
            g2.drawString(num, x, startY + (i - 1) * lineHeight);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
