/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto_compi1_vj26.frontend;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Insets;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTabbedPane;

/**
 * Encabezado personalizado para cada pestaña del JTabbedPane. Muestra el nombre
 * del archivo y un botón "×" para cerrarla.
 *
 * Uso: tabbedPane.setTabComponentAt(index, new TabHeader(tabbedPane, title,
 * onClose));
 *
 * @author david
 */
public class TabHeader extends javax.swing.JPanel {

    private final JLabel titleLabel;

    public TabHeader(JTabbedPane tabbedPane, String title, Runnable onClose) {
        super(new FlowLayout(FlowLayout.LEFT, 0, 0));
        setOpaque(false);

        // --- Título ---
        this.titleLabel = new JLabel(title);
        this.titleLabel.setFont(new Font("SansSerif", Font.PLAIN, 12));
        this.titleLabel.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 6));

        // ---  Botón cerrar ---
        JButton closeBtn = new JButton("×");
        closeBtn.setPreferredSize(new Dimension(18, 18));
        closeBtn.setFont(new Font("SansSerif", Font.BOLD, 12));
        closeBtn.setMargin(new Insets(0, 0, 0, 0));
        closeBtn.setFocusPainted(false);
        closeBtn.setBorderPainted(false);
        closeBtn.setContentAreaFilled(false);
        closeBtn.setForeground(new Color(100, 100, 100));
        closeBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        closeBtn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                closeBtn.setForeground(new Color(200, 50, 50));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                closeBtn.setForeground(new Color(100, 100, 100));
            }
        });

        closeBtn.addActionListener(e -> {
            if (onClose != null) {
                onClose.run();
            }
        });

        add(this.titleLabel);
        add(closeBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Actualiza el título mostrado (usado cuando se guarda o modifica el archivo).
    public void setTitle(String title) {
        this.titleLabel.setText(title);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
